- lib/pubid/iso/identifier.rb
- lib/pubid/iso/parser.rb
- lib/pubid/iso/urn.rb
> Clean up parsing for "Cor of Amd"

- lib/pubid/iso/identifier.rb
- lib/pubid/iso/urn.rb
https://github.com/metanorma/pubid-iso/pull/18#discussion_r821457187
> Rename URN class to Urn

- lib/pubid/iso/identifier.rb
- lib/pubid/iso/parser.rb
- lib/pubid/iso/urn.rb
> Parse all copublishers separately

- lib/pubid/iso/parser.rb
- lib/pubid/iso/transformer.rb
- lib/pubid/iso/urn.rb
- spec/pubid_iso/identifier_spec.rb
- spec/pubid_iso/parser_spec.rb
> Handle draft stages for IWA

- lib/pubid/iso/urn.rb
- spec/pubid_iso/identifier_spec.rb
> Add amendment and corrigendum default version (v1) when version is missing

- .github/workflows/rake.yml
> Add GHA for Ruby 3.1

- README.adoc
> Incorporate Metanorma documentation of ISO PubID to README

- lib/pubid/iso/identifier.rb
- lib/pubid/iso/version.rb
Need to use together with Pubid::Ieee parser.
> Accept parsed input for Identifier.parse for combining parsing rules with another parsers

- lib/pubid/iso/identifier.rb
- lib/pubid/iso/identifier/french.rb
- lib/pubid/iso/identifier/russian.rb
> Return Pubid::Iso::Identifier.year without formatting

- lib/pubid/iso/parser.rb
- spec/pubid_iso/identifier_spec.rb
> Parse corrigendum and amendment without document's year

- lib/pubid/iso.rb
- lib/pubid/iso/identifier.rb
- lib/pubid/iso/parser.rb
- lib/pubid/iso/urn.rb
- spec/pubid_iso/identifier_spec.rb
closes #41 
It's not a complete version, I need more examples to finish it.
> Parse technical committee PubIDs

- lib/pubid/iso/identifier.rb
- lib/pubid/iso/urn.rb
> Add separate stage for URN

- lib/pubid/iso/identifier.rb
- pubid-iso.gemspec
- spec/pubid_iso/identifier_spec.rb
> Use "ISO" publisher when publisher omitted

- lib/pubid/iso/parser.rb
- lib/pubid/iso/renderer/base.rb
- lib/pubid/iso/renderer/dir.rb
- lib/pubid/iso/renderer/urn-dir.rb
- lib/pubid/iso/supplement.rb
- lib/pubid/iso/transformer.rb
- pubid-iso.gemspec
- spec/pubid_iso/identifier_spec.rb
- spec/pubid_iso/supplemnent_spec.rb
> Replace confusing parameter "number" with "year" for supplements

- lib/pubid/iso/renderer/base.rb
- spec/pubid_iso/identifier_spec.rb
> Use short abbreviation for stage with document type for DIS and FDIS

- lib/pubid/iso/amendment.rb
- lib/pubid/iso/corrigendum.rb
- lib/pubid/iso/errors.rb
- lib/pubid/iso/identifier.rb
- lib/pubid/iso/renderer/base.rb
- lib/pubid/iso/stage.rb
- lib/pubid/iso/supplement.rb
- lib/pubid/iso/transformer.rb
- spec/pubid_iso/identifier_spec.rb
> Render short version identifiers for supplements with FDIS and DIS stages

- lib/pubid/iso/errors.rb
- lib/pubid/iso/identifier.rb
- spec/pubid_iso/identifier_spec.rb
> Add test for creating amendment without year

- lib/pubid/iso/errors.rb
- lib/pubid/iso/identifier.rb
- spec/pubid_iso/identifier_spec.rb
> Raise an error when trying to apply iteration for IS stage document

- lib/pubid/iso/identifier.rb
- lib/pubid/iso/parser.rb
- lib/pubid/iso/transformer.rb
- spec/pubid_iso/identifier_spec.rb
- spec/pubid_iso/parser_spec.rb
> Use type attribute for DIR documents

- lib/pubid/iso/parser.rb
- lib/pubid/iso/transformer.rb
- pubid-iso.gemspec
- spec/pubid_iso/identifier_spec.rb
> Accept hash params instead of class for amendments and corrigendums

- lib/pubid/iso/identifier.rb
- lib/pubid/iso/supplement.rb
- spec/pubid_iso/identifier_spec.rb
> Accept stage as symbol or string

- lib/pubid/iso/errors.rb
- lib/pubid/iso/identifier.rb
- lib/pubid/iso/renderer/base.rb
- spec/pubid_iso/identifier_spec.rb
> Raise an error when trying to render URN for document with supplement but without edition

- lib/pubid/iso/identifier.rb
- lib/pubid/iso/renderer/base.rb
- spec/pubid_iso/identifier_spec.rb
> Make rendering PRF stage optional

- lib/pubid/iso/renderer/dir.rb
- spec/pubid_iso/identifier_spec.rb
> Render language for DIR documents

- lib/pubid/iso/errors.rb
- lib/pubid/iso/harmonized_stage_code.rb
- lib/pubid/iso/identifier.rb
- lib/pubid/iso/stage.rb
- lib/pubid/iso/supplement.rb
- spec/pubid_iso/harmonized_stage_code_spec.rb
- spec/pubid_iso/identifier_spec.rb
- spec/pubid_iso/stage_spec.rb
> Accept stage codes

- lib/pubid/iso/renderer/base.rb
- lib/pubid/iso/stage.rb
- spec/pubid_iso/identifier_spec.rb
- spec/pubid_iso/stage_spec.rb
- spec/pubid_iso/supplemnent_spec.rb
> Add tests for FDTS and DTS short codes

- lib/pubid/iso/identifier.rb
- spec/pubid_iso/identifier_spec.rb
> Use :ref_dated_long format as default rendering format

- README.adoc
- lib/pubid/iso/identifier.rb
> Update documentation on how to use this gem

- lib/pubid/iso/errors.rb
- lib/pubid/iso/identifier.rb
- spec/pubid_iso/identifier/create_new_identifier_spec.rb
- spec/pubid_iso/identifier/identifier_spec.rb
> Raise an error for document with supplement when edition year or stage is not provided

- README.adoc
- lib/pubid/iso/errors.rb
- lib/pubid/iso/identifier.rb
- spec/pubid_iso/identifier/create_new_identifier_spec.rb
- spec/pubid_iso/identifier/identifier_spec.rb
> Raise an error when iteration provided without stage

- README.adoc
> Update documentation on how to apply supplements

- README.adoc
- lib/pubid/iso/identifier.rb
- lib/pubid/iso/renderer/base.rb
- lib/pubid/iso/renderer/french.rb
- lib/pubid/iso/renderer/russian.rb
- lib/pubid/iso/stage.rb
- spec/pubid_iso/identifier/identifier_spec.rb
- spec/pubid_iso/renderer/base_spec.rb
- spec/pubid_iso/stage_spec.rb
> Return typed_stage_abbrev for identifier

- lib/pubid/iso/identifier.rb
- spec/pubid_iso/identifier/create_new_identifier_spec.rb
> Remove urn_stage that we are not using anymore

- .github/workflows/release.yml
- lib/pubid/iso.rb
- lib/pubid/iso/errors.rb
- lib/pubid/iso/identifier.rb
- lib/pubid/iso/renderer/base.rb
- lib/pubid/iso/renderer/dir.rb
- lib/pubid/iso/renderer/french.rb
- lib/pubid/iso/renderer/russian.rb
- lib/pubid/iso/renderer/urn.rb
- lib/pubid/iso/supplement.rb
- lib/pubid/iso/transformer.rb
- lib/pubid/iso/type.rb
- spec/pubid_iso/amendment_spec.rb
- spec/pubid_iso/corrigendum_spec.rb
- spec/pubid_iso/identifier/create_new_identifier_spec.rb
- spec/pubid_iso/identifier/dir_spec.rb
- spec/pubid_iso/identifier/identifier_spec.rb
- spec/pubid_iso/renderer/base_spec.rb
- spec/pubid_iso/type_spec.rb
- spec/support/convert_pubid.rb
@ronaldtse what do you think?
But I didn't remove backward compatibility, still possible to add supplements to main identifier.
closes #130
> Supplement as main identifier

- spec/pubid_iso/identifier/identifier_spec.rb
> Add test for language rendering for URN and identifier without supplement

- spec/pubid_iso/identifier/identifier_spec.rb
> Add test for URN rendering of TS type identifier

- lib/pubid/iso/renderer/base.rb
- lib/pubid/iso/typed_stage.rb
- spec/pubid_iso/identifier/create_new_identifier_spec.rb
- spec/pubid_iso/typed_stage_spec.rb
> Fix typed stage rendering

- Gemfile
- lib/pubid/iso/renderer/base.rb
- lib/pubid/iso/renderer/dir.rb
- lib/pubid/iso/renderer/french.rb
- lib/pubid/iso/renderer/russian.rb
- lib/pubid/iso/renderer/tc.rb
- lib/pubid/iso/transformer.rb
- lib/pubid/iso/type.rb
- lib/pubid/iso/typed_stage.rb
- pubid-iso.gemspec
Depends on https://github.com/metanorma/pubid-core/pull/9
> chore: cleanup publisher rendering

- lib/pubid/iso/identifier/amendment.rb
- lib/pubid/iso/identifier/base.rb
- lib/pubid/iso/identifier/corrigendum.rb
- lib/pubid/iso/identifier/directives.rb
- lib/pubid/iso/identifier/guide.rb
- lib/pubid/iso/identifier/international_standard.rb
- lib/pubid/iso/identifier/international_standardized_profile.rb
- lib/pubid/iso/identifier/publicly_available_specification.rb
- lib/pubid/iso/identifier/recommendation.rb
- lib/pubid/iso/identifier/supplement.rb
- lib/pubid/iso/identifier/technical_committee.rb
- lib/pubid/iso/identifier/technical_report.rb
- lib/pubid/iso/identifier/technical_specification.rb
- spec/pubid_iso/identifier/base_spec.rb
- spec/pubid_iso/identifier/create_new_identifier_spec.rb
- spec/pubid_iso/identifier/dir_spec.rb
- spec/pubid_iso/identifier/international_standard_spec.rb
- spec/pubid_iso/identifier/technical_report_spec.rb
> Fix #typed_stage_abbrev and typed_stage_name output for normal stages

- lib/pubid/iso/identifier/base.rb
- lib/pubid/iso/identifier/supplement.rb
- lib/pubid/iso/parser.rb
- lib/pubid/iso/renderer/supplement.rb
- spec/pubid_iso/identifier/base_spec.rb
> Parse "Suppl" ISO PubIDs

- spec/pubid_iso/identifier_spec.rb
> feat: Add test for "ISO/IEC FDIS 23090-14/DAmd 1", fixes #178

- spec/pubid_iso/identifier_spec.rb
> feat: incorporate test for "ISO/IEC FDIS 23008-1/WD Amd 1", fixes #150

- spec/pubid_iso/identifier/recommendation_spec.rb
> Add tests on addendum for recommenation creation

- README.adoc
- lib/pubid/iso/identifier/base.rb
- spec/pubid_iso/identifier_spec.rb
> Add root identifier accessor

- README.adoc
> Add documentation on identifier's type

- lib/pubid/iso/renderer/supplement.rb
- spec/pubid_iso/identifier/supplement_spec.rb
> Add tests on supplements creation

- README.adoc
> feat: update README

- lib/pubid/iso/identifier/base.rb
- spec/pubid_iso/identifier/create_new_identifier_spec.rb
> Resolve typed stage by provided harmonized code

- lib/pubid/iso/renderer/urn-amendment.rb
- lib/pubid/iso/renderer/urn-corrigendum.rb
- spec/pubid_iso/identifier/amendment_spec.rb
> Remove publisher from amendment and corrigendum part of URN

- lib/pubid/iso/identifier/international_standard.rb
- spec/pubid_iso/identifier_spec.rb
- stages.yaml
> Fix PRF stage typed stage name and abbreviation for IS type

- lib/pubid/iso/identifier/amendment.rb
- lib/pubid/iso/identifier/corrigendum.rb
- lib/pubid/iso/identifier/guide.rb
- lib/pubid/iso/identifier/international_standard.rb
- lib/pubid/iso/identifier/international_standardized_profile.rb
- lib/pubid/iso/identifier/international_workshop_agreement.rb
- lib/pubid/iso/identifier/publicly_available_specification.rb
- lib/pubid/iso/identifier/supplement.rb
- lib/pubid/iso/identifier/technical_report.rb
- lib/pubid/iso/identifier/technical_specification.rb
- lib/pubid/iso/identifier/technology_trends_assessments.rb
- pubid-iso.gemspec
- spec/pubid_iso/identifier/amendment_spec.rb
- spec/pubid_iso/identifier/create_new_identifier_spec.rb
closes #193 
Part of the fix in updated pubid-core: https://github.com/metanorma/pubid-core/releases/tag/v1.5.1
> Supplement stage fix

- spec/pubid_iso/identifier_spec.rb
> Add tests for non-IS PubIDs that use PRF typed stage

- lib/pubid/iso/renderer/base.rb
- lib/pubid/iso/renderer/international_standardized_profile.rb
- lib/pubid/iso/renderer/international_workshop_agreement.rb
- lib/pubid/iso/renderer/publicly_available_specification.rb
- lib/pubid/iso/renderer/recommendation.rb
- lib/pubid/iso/renderer/technical_report.rb
- lib/pubid/iso/renderer/technical_specification.rb
- lib/pubid/iso/renderer/technology_trends_assessments.rb
- spec/pubid_iso/identifier_spec.rb
> Render addendum for all types (not only recommendation)

- lib/pubid/iso/identifier/amendment.rb
- lib/pubid/iso/identifier/corrigendum.rb
- spec/pubid_iso/identifier/amendment_spec.rb
- spec/pubid_iso/identifier_spec.rb
> Don't raise an error when amendment's or corrigendum's base document don't have edition year or stage

- spec/pubid_iso/identifier_parsing_spec.rb
> Add identifiers examples from latest ISO standards update

- lib/pubid/iso/parser.rb
- spec/pubid_iso/identifier_parsing_spec.rb
> Parse identifiers using unicode hyphen

- lib/pubid/iso.rb
- lib/pubid/iso/identifier/addendum.rb
- lib/pubid/iso/parser.rb
- lib/pubid/iso/renderer/addendum.rb
- lib/pubid/iso/transformer.rb
- spec/pubid_iso/identifier_parsing_spec.rb
> Parse Draft Addenda

- lib/pubid/iso/identifier/international_standard.rb
- lib/pubid/iso/parser.rb
- spec/pubid_iso/identifier_parsing_spec.rb
> Parse ISO DP "Draft Proposal"

- lib/pubid/iso/parser.rb
- spec/pubid_iso/identifier_parsing_spec.rb
- stages.yaml
> Parse ISO FCD

- README.adoc
> Add rubygems badge

- pubid-iso.gemspec
> Remove unnecessary dependencies

- lib/pubid/iso/renderer/base.rb
- lib/pubid/iso/transformer.rb
- pubid-iso.gemspec
- spec/pubid_iso/identifier/tc_spec.rb
- spec/pubid_iso/identifier_parsing_spec.rb
Related to issue with copublishers order here https://github.com/metanorma/pubid-ieee/pull/103#discussion_r1239509238
> Preserve copublishers order

- lib/pubid/iso/identifier/base.rb
- pubid-iso.gemspec
related https://github.com/metanorma/pubid-iec/issues/127
> Move "typed stage" related methods to pubid-core

- lib/pubid/iso/identifier/base.rb
- spec/pubid_iso/identifier/create_new_identifier_spec.rb
> Accept hash for base and join_document Base#new parameters

- lib/pubid/iso.rb
- lib/pubid/iso/identifier/data.rb
- lib/pubid/iso/renderer/data.rb
- spec/pubid_iso/identifier_parsing_spec.rb
- spec/support/convert_pubid.rb
> Parse DATA type

- lib/pubid/iso/identifier/base.rb
- lib/pubid/iso/parser.rb
- lib/pubid/iso/renderer/dir.rb
- lib/pubid/iso/renderer/supplement.rb
- lib/pubid/iso/transformer.rb
- spec/fixtures/iso-pubid-directives.txt
- spec/pubid_iso/identifier/create_new_identifier_spec.rb
- spec/pubid_iso/identifier/dir_spec.rb
- spec/pubid_iso/identifier_parsing_spec.rb
> Parse "ISO/IEC JTC 1 DIR" identifiers

- lib/pubid/iso/identifier/base.rb
- pubid-iso.gemspec
> Convert "part" and "tctype" parameters to string

- spec/pubid_iso/identifier/dir_spec.rb
- spec/pubid_iso/identifier_parsing_spec.rb
- spec/support/convert_pubid.rb
> Do #to_h round trip for all pubid->pubid tests

- lib/pubid/iso/identifier/supplement.rb
- spec/pubid_iso/identifier_spec.rb
> Allow empty publisher for supplement

- pubid-iso.gemspec
> Update pubid-core to 1.12.4

- .github/workflows/dependent-tests.yml
> #260 add dependent-tests workflow

- lib/pubid/iso/renderer/supplement.rb
- spec/pubid_iso/identifier_parsing_spec.rb
> Fix PRF stage rendering for supplements

- lib/pubid/iso/identifier/extract.rb
- lib/pubid/iso/renderer/urn-extract.rb
- spec/pubid_iso/identifier_parsing_spec.rb
> Render URN for extract identifiers

- lib/pubid/iso.rb
- pubid-iso.gemspec
related to https://github.com/metanorma/pubid/issues/9
> Add prefixes for improved parser matching

- lib/pubid/iso/renderer/technical_committee.rb
- spec/pubid_iso/identifier/create_new_identifier_spec.rb
related to https://github.com/metanorma/metanorma-iso/issues/1195
> Do not render stage for TC identifiers

- README.adoc
> Update README for correct format reference

- .gitignore
- lib/pubid/iso/identifier/base.rb
- lib/pubid/iso/identifier/supplement.rb
- lib/pubid/iso/parser.rb
- lib/pubid/iso/parser_urn.rb
- lib/pubid/iso/transformer.rb
- spec/pubid_iso/identifier_parsing_spec.rb
- spec/spec_helper.rb
- spec/support/convert_pubid.rb
> Add URN parser
